[project]
name = "rensa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mikoushi", email = "eduardo.ramarti@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=1.4.0",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.1",
    "langchain-openai>=1.6.0",
    "psycopg2-binary>=2.9.12",
    "sqlalchemy>=2.0.52",
]

[project.scripts]
rensa = "rensa:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
